version: "3.3"
services:
  talker:
    image: demo
    container_name: talker
    networks:
      - proxynet
    command: bash -c "/startup-vnc.sh & ros2 launch ./root/launch/talker_launch.py"

  listener:
    image: demo
    container_name: listener
    networks:
      - proxynet
    command: bash -c "/startup-vnc.sh & ros2 launch ./root/launch/listener_launch.py"

  sniffer:
    image: ffeldhaus/wireshark
    container_name: wireshark
    privileged: true
    restart: unless-stopped
    ports:
      - "14500:14500"
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
